### ISSUE TITLE
integrate settings component into Fink

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-fink#14] opened 2024-04-10 13:14 UTC
As Sherlock we want to rollout the settings component in Fink as well.

**Comment by NiklasBuchfink** [comment] 2024-04-10 13:48
Duplicate of [FINK-21](https://linear.app/opral/issue/FINK-21/introduce-inlang-settings-to-fink)

**Closed by NiklasBuchfink** 2024-04-10 13:48 UTC
