### ISSUE TITLE
Newlines not committed correctly in fink

### ISSUE THREAD

**Issue by LukasHechenberger** [opral/inlang-fink#38] opened 2024-06-15 17:21 UTC
Hi, when i enter a text in fink newlines get messed up on commit:

Entering

```
Message

Header
- Point 1
- Point 2
```

will get committed as

```
Message
Header- Point 1-Point 2
```

This messes up a lot, I cannot use fink any more at the moment...

Also (may be related): When I copy the same text from fink to my local text editor the original message transforms to:

```
Message

Header

- Point 1

- Point 2
```

**Comment by NiklasBuchfink** [comment] 2024-06-17 09:27
@LukasHechenberger Thank you for opening this.

I have tried it myself and it looks like this in the committed code:
![image](https://github.com/opral/inlang-fink/assets/59048346/b129820e-d8af-4823-b4c6-e320da29ac62)

Is that what you would expect or does it look different in your commit?
And very important for reproduction, do you use Mac or Windows?

**Comment by NiklasBuchfink** [comment] 2024-06-17 11:59
@LukasHechenberger This will be solved when we introduce our inlang editor component in Fink (https://github.com/opral/monorepo/tree/main/inlang/source-code/message-bundle-component).

Please wait until we have this ready, as it allows us to fix issues with the editing experience for all apps.

**Comment by LukasHechenberger** [comment] 2024-06-17 12:00
Alright, thanks. If you can't reproduce it: I'm using Safari on macOS.

**Closed** 2024-12-17 14:50 UTC
